### ISSUE TITLE
Mac App Store Special NWjs Build

### ISSUE THREAD

**Issue by alexeyst** [nwjs/nw.js#3609]
Dear @rogerwang 

I want to open an issue on behalf of a community of people who're happy users of NWjs, and would like to submit their apps to Mac App Store.

Right now, the process is very complicated; it is not supported by default, and everything is based on the work of a few enthusiasts who made this happen.

There was an issue open about this where you have once confirmed your interest in supporting this, but it was since then closed.

Let me bring in the initial comment that describes the situation: https://github.com/nwjs/nw.js/issues/3258#issuecomment-83075536

Since then, @johansatge has written a detailed [guide about submitting NWjs to App Store](https://github.com/johansatge/nwjs-macappstore), so having that and the [custom-built binary](https://github.com/alexeyst/node-webkit-macappstore) helps, but still isn't as good as having an official build with App Store support, which we all hope you could introduce.

Currently, neither NWjs nor Electron supports this, so having official build in NWjs will give it an edge!

Please see the original request below. Look forward to hearing from you!

---

... There was a pull request by @trevorlinton that was open for a long time, but then closed. Here's the [PR in question](https://github.com/nwjs/chromium.src/pull/17).

Now, this was done for an older version of Chromium and node-webkit, so my patch in [here](https://github.com/alexeyst/node-webkit-macappstore) was based on this work but introduced more changes to support successful Mac App Store submission.

However, it is important to note that my patch only solves the submission problem, and as I don't have a complete development environment around Chromium I did not run its tests on this; more to that end, the patch disables certain parts of Chromium restricted by Apple rather than re-implementing them, so I guess you as an owner/maintainer of this could make a decision of what is the best way to incorporate this. 

Lastly, there's another complication in the process—every time NW starts using new Chromium, a respective change should be made until Chromium project stops using QTKit and other blocked private APIs in the first place.

So, IMHO, setting up a special build for Mac App Store would be of a great value. I will be happy to test that build on my app and ensure successful submission, if you'd be willing to setup one. 

This would be really very helpful, as so far the need of custom-building the NW executable and update / rebase the patch every time makes the adoption of NW's updates for Mac App Store users much more complicated. So, @rogerwang, thank you very much for your attention to this issue, and I hope it can be solved one day!

**Comment by rogerwang** [comment]
Thanks for the survey. Supporting Mac app store submission is one of the top things on the todo list. Currently I'm focused on 0.13.0 development so I'll try to support it in that version, or probably in the next 0.12 version if there is one.

**Comment by rogerwang** [comment]
I've merged the 2 patches into the 'mas' branch and setup a buildbot for it. Once the built binary is verified to be good I'll merge it into the 'nw12' branch.

**Comment by sujkh85** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

sujkh@naver.com 님께 보내신 메일 <Re: [nw.js] Mac App Store Special NWjs Build (#3609)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by alexeyst** [comment]
Thank you so much @rogerwang 

I couldn't be happier. I will test this on the App Store, and I hope @johansatge will join. 

The recent build of `mas` branch failed because there was one `MAC_APP_STORE` define not changed to the newer `NWJS_MAS` used elsewhere. This is on line 1072 in `chrome/browser/process_singleton_posix.cc`. Hope you can get it to build, and then we will test it with App Store.

Thanks again for your prompt response!

**Comment by johansatge** [comment]
Hi,

great news !

I'll test the build as soon as it's ready.

**Comment by rogerwang** [comment]
@alexeyst it's fixed.

**Comment by alexeyst** [comment]
Thank you! @rogerwang Will test and report.

**Comment by johansatge** [comment]
Hello,

FIY the `0.12.2` binary submitted on @alexeyst repo has been approved by Apple a few hours ago :+1:

**Comment by oransel** [comment]
I am using version 0.12.2 with entitlements:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
</dict>
</plist>

and the following command to sign the main app:

codesign --force --verify --verbose --entitlements ./roku.entitlements --sign <key> ./<appname>.app

All other 4 executables in <appname>.app are also signed with the same key. However, when the app starts, it crashes with:

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Any ideas?

**Comment by alexeyst** [comment]
Hey @oransel!

Have you tried the signing script? See [here](https://github.com/johansatge/nwjs-macappstore/wiki/Signing-the-app) for details!

**Comment by yangwao** [comment]
This is great news that we have new 0.12.2 for MAS! :) 
However, I've been successful with submitting @alexeyst modified version 0.11.5, but now I'm struggling with 0.12.2 :disappointed: 
I also tried signing described as [here](https://github.com/johansatge/nwjs-macappstore/wiki/Signing-the-app), but have problem with CFBundleIdentifier Collision.

		`ERROR ITMS-90511: "CFBundleIdentifier Collision. The Info.plist CFBundleIdentifier value 'io.nwjs.nw.helper.EH' of 'myapp.app/Contents/Frameworks/nwjs Helper EH.app' is already in use by another application."
		ERROR ITMS-90511: "CFBundleIdentifier Collision. The Info.plist CFBundleIdentifier value 'io.nwjs.nw.helper.NP' of 'myapp.app/Contents/Frameworks/nwjs Helper NP.app' is already in use by another application."
		ERROR ITMS-90511: "CFBundleIdentifier Collision. The Info.plist CFBundleIdentifier value 'io.nwjs.nw.helper' of 'myapp.app/Contents/Frameworks/nwjs Helper.app' is already in use by another application."
		ERROR ITMS-90255: "The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app."`

**Comment by johansatge** [comment]
Hi,

@yangwao, thanks for reporting this !

Indeed, keeping the default `CFBundleIdentifier` in the helper apps is not good.

I have added a step in the guide ([Configuring children apps](https://github.com/johansatge/nwjs-macappstore/wiki/Configuring-children-apps)), and updated [Signing the app](https://github.com/johansatge/nwjs-macappstore/wiki/Signing-the-app) accordingly.

It should be better, let me know if it works !

Cheers

**Comment by johansatge** [comment]
Also, all those steps are getting boring :)

We should make a script to automate the build; it could be based on [node-webkit-builder](https://www.npmjs.com/package/node-webkit-builder) for instance.

**Comment by yangwao** [comment]
Yeah, it's boredom, mostly waiting for automatic validation from Application Loader.

Son of Odin, looks it works! It passes validation and happily uploaded to App Store. Now I should just wait if everything is ok there :)
I've just made this snippet for changing CFBundleIdentifiers. I could also publish my whole signing script
'echo -e "Modify nwjs Info.plist CFBundleIdentifiers to your bundleid"
sed -i '' 's/io.nwjs.nw.helper/'$bundleid'/g' $app"/Contents/Frameworks/nwjs Helper.app/Contents/Info.plist"
sed -i '' 's/io.nwjs.nw.helper.EH/'$bundleid'/g' $app"/Contents/Frameworks/nwjs Helper EH.app/Contents/Info.plist"
sed -i '' 's/io.nwjs.nw.helper.NP/'$bundleid'/g' $app"/Contents/Frameworks/nwjs Helper NP.app/Contents/Info.plist"'

**Comment by johansatge** [comment]
Hi,

I have published a node module / CLI tool to automate the build: [here](https://github.com/johansatge/nwjs-macappstore-builder/)

Comments very welcome :)

Have a nice day

**Comment by oransel** [comment]
@yangwao very nice app. I found 2 issues with it. 

1. I had to add --force to signing command. It kept reporting that the helper apps were already signed.

2. I added identityInstaller to the config. The installer needs to be signed by another cert. Since I have a few certs, it was picking the iOS cert to sign everything.

Now, it is all compiled and signed, but cannot start the app. It still crashes the same way.

**Comment by oransel** [comment]
@yangwao here are the errors. I am not too sure about the first one but the rest seem to need unique bundle identifiers.

ERROR ITMS-90135: "The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools."

ERROR ITMS-90334: "Bundle identifier mismatch. The executable at nwjs Helper EH in <appname>.app/Contents/Frameworks/nwjs Helper EH.app has been signed with identifier 'com.oransel.<appname>' which does not match the bundle identifier 'com.oransel.<appname>.helper.EH'."

ERROR ITMS-90334: "Bundle identifier mismatch. The executable at nwjs Helper NP in <appname>.app/Contents/Frameworks/nwjs Helper NP.app has been signed with identifier 'com.oransel.<appname>' which does not match the bundle identifier 'com.oransel.<appname>.helper.NP'."

ERROR ITMS-90334: "Bundle identifier mismatch. The executable at nwjs Helper in <appname>.app/Contents/Frameworks/nwjs Helper.app has been signed with identifier 'com.oransel.<appname>' which does not match the bundle identifier 'com.oransel.<appname>.helper'."

**Comment by oransel** [comment]
@yangwao i was able to fix the last 3. now only issue outstanding is the executable could not be re-signed for submission to the App Store. I am guessing this is happening since it has more than 1 app inside an app signed by different certs.

**Comment by johansatge** [comment]
Hi @oransel, thanks for your help ! I have merged your [PR](https://github.com/johansatge/nwjs-macappstore-builder/pull/1) and updated the build module to `3.0.0`.

The [Signing the app](https://github.com/johansatge/nwjs-macappstore/wiki/Signing-the-app) page has also been updated; as you said in your PR, adding the bundle ID with `codesign -i` is not necessary.

I'm not sure about the *force* issue, but it may not be a good idea to try to sign the same app more than once.

**Comment by shaynem** [comment]
I can't use this myself as the app can't be sandboxed, but i've had a look
at the code etc and you have done good work and thanks for sharing with the
rest of the community.

**Comment by oransel** [comment]
Hi @johansatge and @alexeyst . I'm still having issues with sandboxing and signing. 

* When I run the app, the helper crashes with 'Could not set sandbox profile data: Operation not permitted (1)'.
* Then comes 2 new Mac Store issues.

```
ERROR ITMS-90255: "The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app."

ERROR ITMS-90135: "The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools."```

Any thoughts?

**Comment by yangwao** [comment]
@johansatge that totaly looks like mine 67 lined bash script :smile: now gruntify/gulpify :stuck_out_tongue: I
I will let you guys know in like 5 days when reply from Itunes store hit me up.

I've been using --force If I signing second time, but mostly I'm trying signing only fresh build, i.e. 
    $ codesign --force --verify --verbose --sign "$identity" -i $bundleid --entitlements $entitlementschild "$app/Contents/Frameworks/nwjs Helper.app/"

**Comment by johansatge** [comment]
@oransel I got your error once, because of files that did not have the right permissions (don't remember why though).

```
ERROR ITMS-90255: "The installer package includes files that are only readable by the root user. This will prevent verification of the application's code signature when your app is run. Ensure that non-root users can read the files in your app."
```

It was resolved by setting manually the permissions, before signing:

```bash
cd YourApp.app/Contents/Resources/app.nw && find . -type f -exec chmod 664 {} \;
```

**Comment by oransel** [comment]
@johansatge that fixed the permission issue. Thank you.

**Comment by oransel** [comment]
Remaining issues:

* When I run the app, the helper crashes with 'Could not set sandbox profile data: Operation not permitted (1)'.

* ERROR ITMS-90135: "The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools."

**Comment by alexeyst** [comment]
Hey @oransel 

Re crash: does it happen on an empty app too? It is important to only sign the app once, and avoid a repeated signature flow. 

Re ERROR ITMS-90135: are you using C/C++ node modules? When you build them, there should be no *.o or *.obj files remaining in the build directories.

**Comment by oransel** [comment]
Hi @alexeyst 

Yes the crash is happening on an empty app too. The console log doesn't mention certificate issue. It seems like sandboxing issue.

7/9/15 5:50:24.610 PM sandboxd[409]: ([46188]) nwjs Helper(46188) deny forbidden-sandbox-reinit
7/9/15 5:50:24.840 PM sandboxd[409]: ([46192]) nwjs Helper(46192) deny forbidden-sandbox-reinit
7/9/15 5:50:24.872 PM sandboxd[409]: ([46193]) nwjs Helper(46193) deny forbidden-sandbox-reinit

**Comment by alexeyst** [comment]
Okay, so I believe it is a signing issue. Could you please paste the complete set of commands you're using to sign it?

Sent from my iPhone

On Jul 9, 2015, at 5:53 PM, Mustafa Oransel <notifications@github.com> wrote:

Hi @alexeyst

Yes the crash is happening on an empty app too. The console log doesn't mention certificate issue. It seems like sandboxing issue.

7/9/15 5:50:24.610 PM sandboxd[409]: ([46188]) nwjs Helper(46188) deny forbidden-sandbox-reinit
7/9/15 5:50:24.840 PM sandboxd[409]: ([46192]) nwjs Helper(46192) deny forbidden-sandbox-reinit
7/9/15 5:50:24.872 PM sandboxd[409]: ([46193]) nwjs Helper(46193) deny forbidden-sandbox-reinit

**Comment by oransel** [comment]
It seems to be a chrome issue: https://bitbucket.org/chromiumembedded/cef/issues/1204

**Comment by broderix** [comment]
Hi folks!
I have just got a reject from MAS 2.31
if you don't use location in your app then remove "com.apple.security.personal-information.location" from Info.plist

**Comment by johansatge** [comment]
Hi @broderix,

if your really need the user location, you may explain why to the validation team (in the *Resolution Center*); then they should accept the app.

Sometimes they just reject a build because they want explanations on a feature.

**Comment by rogerwang** [comment]
The 'mas' branches in chromium repo and blink repo have been merged into nw12 branch. It will be released with 0.12.3 as additional build.
