### ISSUE TITLE
[3668:3668:0114/222444:FATAL:browser_view.cc(530)] Check failed: browser->is_type_popup(). opening browser window.

### ISSUE THREAD

**Issue by freddyb** [nwjs/nw.js#4246]
When clicking on pictures in signal-desktop running in nwjs-sdk-v0.13.0-beta3-linux-x64:

> [3668:3668:0114/222444:FATAL:browser_view.cc(530)] Check failed: browser->is_type_popup(). opening browser window.
> # 0 0x7f1d8182872e <unknown>
> 
> Aborted

Will follow up with steps to repeat once @ttaubert publishes his guide on how to run signal-desktop in nwjs.

(Possible duplicate of #3756)
##

**Comment by ttaubert** [comment]
We could also try to figure out what exactly Signal is doing at that moment. Probably opening some link a new window. Then we'd have a smaller example to test with.

**Comment by freddyb** [comment]
I'd debug the event listener, but #4253 prevents me :)

**Comment by ghostoy** [comment]
We fixed a similar issue. Could you try if latest nightly working for you.

**Comment by freddyb** [comment]
Still get the same crash.
The app I'm using, is [a self-built Signal-Desktop, as explained in this blog post](https://timtaubert.de/blog/2016/01/build-your-own-signal-desktop/)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? Or you may refer to #5574.

**Comment by Christywl** [comment]
close until there is more information.
