### ISSUE TITLE
menubar background nw 0.14.5

### ISSUE THREAD

**Issue by herudi** [nwjs/nw.js#4851]
imposible menubar background like electron...

**Comment by ghostoy** [comment]
@herudi What do you mean by "menubar background"?

**Comment by herudi** [comment]
thanks for advanced, here please look it this. 
![nw js menubar](https://cloud.githubusercontent.com/assets/11951458/15307607/d2e060da-1bfe-11e6-899a-74d0af2ad948.png)

how to change background color like here ?
![electron menubar](https://cloud.githubusercontent.com/assets/11951458/15307619/ff0b8acc-1bfe-11e6-9a5f-63304453f889.png)

**Comment by ghostoy** [comment]
@herudi I will fix it by using the standard colors for menubars on Windows and Linux. Do you believe it's necessary to change the color by code?

**Comment by thisKai** [comment]
I would appreciate a Javascript or CSS api for changing the colours of the menus and menubar if it is at all possible, mostly because I find the light menubar very distracting on apps with a dark theme

**Comment by ghostoy** [comment]
The menubar and popup menus will use system theme color. So if you have
dark theme, the menubar will be dark, too.

thisKai <notifications@github.com>于2016年8月3日周三 04:15写道：

**Comment by ghostoy** [comment]
@thisKai FYI. It has not been merged to the LTS version. You can test with latest stable 0.16.0 to see the menubar / context menu color. When you changed the theme, the menubar / context menu color will change as well.

**Comment by blaremc** [comment]
It's really need for dark applications.

**Comment by ghostoy** [comment]
@blaremc It was fixed since 0.16. You can try with latest NW.js builds. BTW, LTS targeted for legacy OSes, like Windows XP/Vista and Mac OS X 10.6 or earlier. So it's not recommended to use it for modern apps.

**Comment by blaremc** [comment]
@ghostoy was fixed what? I couldn't find anything about changing menu background or menu color in documentation :(

**Comment by ghostoy** [comment]
@blaremc The fix was using the default theme color, not a user specified color.

> The menubar and popup menus will use system theme color. So if you have
dark theme, the menubar will be dark, too.

**Comment by pd-l2ork** [comment]
This is still broken on 0.42.3 because the menubar on Ubuntu 20.04 and 22.04 with a dark theme takes on white background and keeps text white, which makes it impossible to read. 0.28.3 does not have this problem, so this is a regression. Not sure about the latest version (0.69.1). That one (for my needs) has other issues that prevent me from using it.
