### ISSUE TITLE
"NW.js is using your microphone"

### ISSUE THREAD

**Issue by darshanshankar** [nwjs/nw.js#4852]
On Windows 10, with nwjs 0.14.5, when using gUM and a microphone, the bottom tray has an icon that says "NW.js is using your microphone" Clicking it reveals a button with the name of my app.

![image](https://cloud.githubusercontent.com/assets/8766412/15277201/f86e9af4-1ab1-11e6-9187-ec65d9cea8b4.png)

I understand this is default Chrome behavior to indicate an app using a mic for user privacy, but how can I disable this or at least rename it to "my app is using your microphone"?

**Comment by rogerwang** [comment]
Will fix this soon. Thanks.

**Comment by jtg-gg** [comment]
@rogerwang have you started working on it? I would like to volunteer

**Comment by rogerwang** [comment]
@jtg-gg great. thanks.

**Comment by jtg-gg** [comment]
@rogerwang I've made a pull request https://github.com/nwjs/chromium.src/pull/18

**Comment by jonwwilkes** [comment]
Disabling the notification altogether is worse than showing the wrong app name.

**Comment by jtg-gg** [comment]
@jonwwilkes 
in my opinion:

1. the tray icon is not much of use for nw.js, for chrome yes, to tell the user which tab / extension is using the microphone
2. we were having similar case for screen sharing, and we choose to disable it
3. if we have 2 different nwjs app running and using the mic, we might have 2 tray icon (haven't test it myself)

**Comment by jonwwilkes** [comment]
@jtg-gg:
1. It's of great use.  In my application that notification would be an important and obvious sign of a serious bug.
2. Chromium (unfortunately) already has a track record of casually dropping in a blob that could turn on the mic: https://bugs.chromium.org/p/chromium/issues/detail?id=500922 thus triggering said bug
3. If we have 2 different apps accessing the mic, nwjs should send the correct app name for each.  That's what the "name" field in the manifest is for, after all.

Btw, @jtg-gg: are you still producing binaries for the rpi? (Sorry to abuse the bug list to ask that, but I don't see a way to send you a message.)

**Comment by jtg-gg** [comment]
@jonwwilkes I would let @rogerwang decide
as for pm, hmm interesting, looks like github doesn't have pm functionality.

answering your question for rpi, yes we still manage it, but I don't think I can share the binary file
but I would be happy to show you the steps / patches to make armv7 build

**Comment by jonwwilkes** [comment]
@jtg-gg: could you post the rpi instructions on the nw.js google group?

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by rogerwang** [comment]
We use a different security model from the one in Chromium browser, so at least this can be disabled. @jonwwilkes 's suggestion could be another feature on top of this. If anyone feel it's needed, please submit another issue to track it.

**Comment by darshanshankar** [comment]
@rogerwang I tried the two most recent 0.14.5 nightly builds (5/19 and 5/20) and this behavior is still present.

**Comment by rogerwang** [comment]
The fix should be in both 0.14 and 0.15. What's the exact 0.14 nightly build were you trying with?

I'll see the sharing screen regression. Thanks.

**Comment by darshanshankar** [comment]
I tried `nwjs-sdk-v0.14.5-win-x64.zip` from these two sources:
http://dl.nwjs.io/live-build/05-19-2016/nw14-cc861be-c26c469-2a9e6e1-5a26102/v0.14.5/
http://dl.nwjs.io/live-build/05-20-2016/nw14-cc861be-c26c469-2a9e6e1-5a26102/v0.14.5/

**Comment by darshanshankar** [comment]
Sorry, I just tried the 05-19-2016 0.14.5 build again and it appears to work, there is no longer a microphone dialog. I must have had a caching issue!

**Comment by rogerwang** [comment]
"X is sharing your screen" is fixed in git and will be available in the next nightly build.
