### ISSUE TITLE
nwjs 0.16.x regression: crashing on link open in webview

### ISSUE THREAD

**Issue by krneticz** [nwjs/nw.js#5226]
Windows 8.1 (but also happening on win 10)
nwjs 0.16.1 64bit SDK (but also happening with 32bit version and with 0.16.0)

nwjs 0.16.x is crashing when setting src to webview. This issue is not reproducible on nwjs 0.15.4. Use attached test application, open it and click on  "Kill me already!" link in the bottom of the page. Crash dump is not created for whatever reason, but I have attached debug.log that is created. 

[nw016_crash_case.zip](https://github.com/nwjs/nw.js/files/426513/nw016_crash_case.zip)

[debug.log.zip](https://github.com/nwjs/nw.js/files/426514/debug.log.zip)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

**Comment by krneticz** [comment]
Issue is still present in live-build/08-22-2016/nw16-1d6387e-f529e82-53e928e-80ede20/v0.16.2/. test on Win 8.1

**Comment by rogerwang** [comment]
That's the previous build before this commit. Nightly build starts after midnight in UTC+8.

**Comment by rogerwang** [comment]
please try http://dl.nwjs.io/live-build/08-23-2016/nw16-b4f50b1-4fe31bb-53e928e-80ede20/v0.16.2/

**Comment by krneticz** [comment]
@rogerwang it is fixed! Thank you very much!
