### ISSUE TITLE
Printing Footer document.href

### ISSUE THREAD

**Issue by denneboomyo** [nwjs/nw.js#5702]
Hi. 
When using `window.print()` the default Print-Preview shows the document location in the footer 
(i.e. chrome­extension://ibkmfehcjphcagmhiocddpidkmjejnfl/index.html)

Is there any way to change the document location only for the print?

nwjs-Version: 0.20.1-sdk
OS: Windows 10 1607

**Comment by conceptualspace** [comment]
unfortunately not with print preview :(

but you can hide the footer with the the nw print api (#4911)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.

Please see the doc change in the commit for usage.

**Comment by conceptualspace** [comment]
THANK YOU ROGER!

but can we also have a headerString to match the footerString? (otherwise the URL still shows at the top of the page)

**Comment by denneboomyo** [comment]
Try changing the Title-Tag in your index.html. For me the header shows the title of the current html document.

**Comment by conceptualspace** [comment]
thanks for the tip --

it works with a static title set via html, but doesn't seem to work when setting the title programmatically via win.title

**Comment by conceptualspace** [comment]
see also #4921

**Comment by conceptualspace** [comment]
so rather than add a headerString, looks like we just need to fix 4921

**Comment by conceptualspace** [comment]
to clarify for anyone who might be scratching their head --

problem 1: [win.title](http://docs.nwjs.io/en/latest/References/Window/#wintitle) is ignored if the title is defined via html tag (#4912). it works as expected when no html title tag exists.

problem 2: print headers only seem to read the title defined by the html title tag, and ignore the title set via nw's win.title

workaround: just use document.title

perhaps if win.title is redundant and broken, the simplest solution is to just drop it from the docs :)
