### ISSUE TITLE
NWJS framework crash with fatal error in , line 0 unimplemented code

### ISSUE THREAD

**Issue by asleepysamurai** [nwjs/nw.js#6335]
NWJS Version : 0.27.2 (SDK)
Operating System : OSX El Capitan (10.11.4)

### Expected behavior

NWJS Framework should not crash

### Actual behavior

NWJS Framework (thread 0) crashes with following message:

````
#
# Fatal error in , line 0
# unimplemented code
#
````

This happens only when I'm running the code in a child process obtained with child_process.fork.

### How to reproduce

Unfortunately, I cannot provide the exact code which triggers this, but I have attached the crash dump which says that the nwjs framework thread 0 crashed with EXC_BAD_INSTRUCTION / EXC_I386_INVOP.

Crash Dump:
https://filebin.ca/3ksfOpZAqRQ4/712953f3-6432-49f5-a79f-200dcb289bb2.dmp

Minidump_stackwalk output (It doesnt seem to be able to find the symbol files even though I've placed them correctly. Not sure whats happening there)
[minidump_stackwalk.txt](https://github.com/nwjs/nw.js/files/1564700/minidump_stackwalk.txt)

**Comment by rogerwang** [comment]
Thanks for reporting. Does it reproduce with 0.27.1 and 0.26.6?

**Comment by asleepysamurai** [comment]
It's reproducible in 0.27.1 but not in 0.26.6. 

As a temp workaround, I'm going to downgrade to 0.26.6.

**Comment by Christywl** [comment]
I also reproduce this error on Linux with nwjs-sdk-v0.27.2.
Launch the app and then close it, you can see this error in the terminal:
```
#
# Fatal error in , line 0
# unimplemented code
#
```
index.html:
`<script src='parent.js'></script>`

parent.js:
```
const cp = require('child_process');
const n = cp.fork('sub.js');

n.on('message', (m) => {
  console.log('PARENT got message:', m);
});

n.send({ hello: 'world' });
```
sub.js:
```
process.on('message', (m) => {
  console.log('CHILD got message:', m);
});
process.send({ foo: 'bar', baz: NaN });
```

**Comment by rogerwang** [comment]
@Christywl does it reproduce with this build: https://dl.nwjs.io/live-build/12-20-2017/nw27-44f34c0-c520573-4f2dbdc-f13e613/v0.27.3/

We fixed a similar issue yesterday in this build.

**Comment by Christywl** [comment]
@rogerwang , this error still appears on this nightly build.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next nightly build.
