### ISSUE TITLE
win.print() "printer" option no longer works.

### ISSUE THREAD

**Issue by tiitremmel** [nwjs/nw.js#6510]
NWJS Version : 0.29.0
Operating System : macOS High Sierra 10.13.3

When settings the options object to {printer: 'foo',autoprint:false} the preview window should show destination printer as described in options, but instead it chooses some other - i don't know if its randomly or OS default.

steps to reproduce
Run `win.print({autoprint:false,printer:'my_printer_device_name'})` on any open window.

Below is attached gif of steps to reproduce.
![nwjs-print-bug](https://user-images.githubusercontent.com/6403731/37343280-b60490f2-26cf-11e8-8642-54ff73713ca4.gif)

**Comment by Christywl** [comment]
I can reproduce this issue with nwjs-sdk-v0.29.0.

**Comment by FiatPax** [comment]
This should be fixed, it was not nwjs's fault. https://chromium.googlesource.com/chromium/src/+log/65.0.3325.146..65.0.3325.162?pretty=fuller&n=10000

You can see it is now fixed in the Chromium's new version, so just get the nwjs 0.29.1

**Comment by rogerwang** [comment]
@Christywl please try again with 0.29.1.

**Comment by Christywl** [comment]
Still have a problem with v0.29.1:
If I clear the data directory `%LOCALAPPDATA%/nwjs`, the printer can be set successfully. If not, the new printer can't be set, it uses the previous one.
The first time:
![image](https://user-images.githubusercontent.com/20039821/37579802-493b5a18-2b7b-11e8-809f-ea3a86713904.png)
The second time:
![image](https://user-images.githubusercontent.com/20039821/37579820-6951b59a-2b7b-11e8-9e89-fe9db5ffcb82.png)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).
