### ISSUE TITLE
0.30.0-beta1 Throwing error inside node enabled worker crashes nw.js

### ISSUE THREAD

**Issue by cTn-dev** [nwjs/nw.js#6544]
NWJS Version : 0.30.0-beta1 SDK 
Operating System : Windows 10 x64

(Some stable builds should also be affected)

### Expected behavior
Error should be thrown and caught by the error handler

### Actual behavior
nw.js crashes, leaving this message in debug.log
`[0401/023407.870:ERROR:http_transport_win.cc(175)] WinHttpCrackUrl: The URL does not use a recognized protocol (0x2ee6)`

### How to reproduce
Executing following code inside node enabled worker (--enable-node-worker) should do the trick (i attached example just in case)

```
onmessage = (event) => {
    console.log('I will try to throw an error in 5 seconds');

    setTimeout(function () {
        throw new Error('Normal Error');
    }, 5000);
};

```
I have been running into this bug quite often (for several months now, previous stable builds should also be affected to some degree) but it came and go randomly leaving me with no way to nail it down, the method above should repro the issue 100%.

[example.zip](https://github.com/nwjs/nw.js/files/1866011/example.zip)

**Comment by cTn-dev** [comment]
@rogerwang could you have a look please?

**Comment by rogerwang** [comment]
Please try this new build, in which we fixed a similar issue:
https://dl.nwjs.io/live-build/nw30/03-28-2018/a3b2369-c51f71f-3997f5c-227a27b/v0.30.0-beta1/

**Comment by cTn-dev** [comment]
Unfortunately this build is still affected (still crashes with the same error in the debug.log as before)

**Comment by rogerwang** [comment]
Does it occur in cases other than in a timer callback?

**Comment by rogerwang** [comment]
btw this is the duplicate of #6153 .

**Comment by cTn-dev** [comment]
It does, the problem is, i don't know under what condition it happens.
In my project i utilize the native http2  node module inside a node worker and it likes to crash randomly when i use "reload app", whats even more bizarre is that after it crashes it sometimes instantly crashes 2-3 times in a row after loading the app, then suddenly starts working again.

The timer callback was so far the only way i could successfully repro it.

Looking at the #6153 you are probably right, i will continue the conversation there.

**Comment by rogerwang** [comment]
There is a workaround there and you can try it.
