### ISSUE TITLE
NW 0.32.2 - CRASH On accessing properties of elements created with createElement

### ISSUE THREAD

**Issue by Jivec** [nwjs/nw.js#6768]
[ac64e008-4454-4660-b279-18e92c33d2f3.zip](https://github.com/nwjs/nw.js/files/2291627/ac64e008-4454-4660-b279-18e92c33d2f3.zip)
Hello,

The problem is happening when im trying to run the exe with the binary files , im using webpack and combining some modules classes to a bundle , no problems if i run it normally. If i compile it to binary with both settings nw-module or not i get a crash, i managed to narrowed it down to a single line.

`    let mx = document.createElement('div');
        
        document.body.appendChild(imx);
        imx.id = "test";
        console.log(imx);`

When trying to access the id of the element it crashes if i remove that line everything works and the element is inserted correctly! 

Thanks in advanced !!!!

**Comment by rogerwang** [comment]
Could you please provide a full example to reproduce?

**Comment by Jivec** [comment]
Ok please try this.

` //core.js
 import t from './test.js';
 let tinst = new  t(db);

 //test,js
 class T{

     constructor(db){
          let imx = document.createElement('div');
          document.body.appendChild(imx);
          imx.id = "test";
          console.log(imx);
     }
 }
export default T;


`

**Comment by Jivec** [comment]
Ok please try this.

//core.js
 import t from './test.js';
 let tinst = new  t(db);

 //test,js
 class T{

     constructor(db){
          let imx = document.createElement('div');
          document.body.appendChild(imx);
          imx.id = "test"; //problem with pointer i guess
          console.log(imx);
     }
 }
export default T;

**Comment by Jivec** [comment]
Please tell me if with this example you can reproduce the crash when using binary.

Thanks in Advance!!

**Comment by rogerwang** [comment]
Please upload a full sample (not code snippet) so we can reproduce it.

**Comment by Jivec** [comment]
The problem persists in 0.32.3 , i reproduced it with a simpler example since the original project consists of many files.
Attached the package.nw you can try it with both 0.32.2 and 0.32.3, found that it happens in both of these versions.

Thanks in Advance once again.

[package.nw.zip](https://github.com/nwjs/nw.js/files/2296445/package.nw.zip)
If you replace the line that test.js is accessing the id property of the newly created element it works (i mean in binary) because if i include the bundle.js without compiling down it just works.

I also found that in prior version of nw.js is working and thats what im using now , but i would love to have the chromium 68 features :)

**Comment by Ziiven** [comment]
Maybe it is the same issue that I encountered #6742

**Comment by rogerwang** [comment]
I can reproduce the crash with 0.32 and it seems fixed in 0.33.0-beta1. Please have a try.

**Comment by rogerwang** [comment]
Thanks for verifying. Will update the beta with Node 10.9 soon.

**Comment by Jivec** [comment]
Still not fixed for me in the complex scenario i described before 

[d4354d0d-4bc2-4c2e-bdc1-66119c341dbe.zip](https://github.com/nwjs/nw.js/files/2299613/d4354d0d-4bc2-4c2e-bdc1-66119c341dbe.zip)

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw33/08-18-2018/575e6aa-93ab45a-f481a11-3cb3442

**Comment by rogerwang** [comment]
@jivec please try to provide a sample. Thanks
