### ISSUE TITLE
webview functionality issue - something went wrong 

### ISSUE THREAD

**Issue by dansachelarie** [nwjs/nw.js#6876]
NWJS Version :
I tried on window/linux with the latest nwjs version (0.34.5) just to load a page inside an webview (www.aa.com) and do a flight serch. It said "Something wrong happend" on the window/linux but in osx it is working. Also if I try in chrome it is working as expected, also tested on a nwjs window without webview and it is also working.

### Expected behavior
The results of the search should appear.

### Actual behavior
"Something wrong happend" message appear on the screen only on linux/window but in osx is working as expected.

### How to reproduce
Just load that website (www.aa.com) in a webview and do a valid flight search.

**Comment by asteriosgr** [comment]
I can confirm.
Tested Versions: NW.js 0.34.1 + 0.34.5 
Conditions of test: webview, Ubuntu x64

When visiting some websites within a webview using nwjs, is breaking some of the expected functionality. Taking a look at the issues described below can provide a better insight on the matter.

The first website is aa.com

Issue 1.

Behavior: 
Performing a search query at aa.com is resulting into a page where something went wrong

Expected behavior: 
A search query regarding flights and schedule should appear based on user’s options.

Issue 2.

Behavior:
Some links that require opening in a new window do not function. This may occur for other links randomly as well. When clicked upon nothing will happen.

Expected behavior:
Links open normally.

The second website is kayak.com

Issue 3.

Behavior:
Clicking login and then register is working. HOWEVER when clicking either gmail or facebook to login there is no functionality. Registration and then logging in is working ok.
Expected behavior:
User should be allowed to login using gmail services or facebook sign in.

Issue 4.

Behavior:
Searching for a hotel or to rent a car (anything other than flights), is not working. A page with a round cursor loading is presented. And then nothing.
Expected behavior:
The requested pages should open normally upon clicking on the link.

The third website is booking.com

Issue 5.

Behavior:
When clicking on login/register a black veil is covering the screen.
Expected behavior:
Open the login/registration form and when clicking anywhere else e.g. on the background, the from should disappear.

Issue 6.

Behavior:
Categories such as flights, accommodations, car rentals  etc ,cannot be clicked upon.
Expected behavior:
They should open the link requested when clicked.

Issue 7.
Accessing any of the categories mentioned in Issue 6, using a different way e.g. via google search produces the following interesting results.
Issue 7.a CARS.BOOKING.COM
Search button is not working.

Isue 7.b OPENTABLE.CO.UK
Login using facebook is not working.

**Comment by rogerwang** [comment]
Could you please try this latest build? It works well for me when load aa.com and search in a webview.

https://dl.nwjs.io/live-build/nw35/11-26-2018/3a11b2178/v0.35.0/

**Comment by asteriosgr** [comment]
Thank you for your response. Your feedback is appreciated. However, that is why I explicitly stated the OS. In windows it is functioning properly. However, when trying Ubuntu I reproduce that.

**Comment by dansachelarie** [comment]
I tested on windows I can confirm that it works, but on linux it is not working, any idea why?

**Comment by rogerwang** [comment]
I just tried on Linux with the latest build and it works for me too.

**Comment by rogerwang** [comment]
That's sure and I'm using this sample:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>My App</title>
  </head>
  <body>
    <webview src="https://www.aa.com/"></webview>
  </body>
</html>
```

**Comment by asteriosgr** [comment]
This is mine:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Test!</title>
  </head>
  <body>
	<webview style='position:absolute;height:800px;width:1200px' src="https://www.google.com"> </webview>
  </body>
</html>
```

**Comment by asteriosgr** [comment]
And when doing a search of any flight in aa.com for example, I get this:
![image](https://user-images.githubusercontent.com/4445313/49072740-91531900-f239-11e8-8ea6-a7bf223c496c.png)

**Comment by rogerwang** [comment]
That error message is from the server, not NW.

**Comment by asteriosgr** [comment]
Yes however, it appears only when doing the search using nwjs+webview in Ubuntu 18.04. Also then check this:
![image](https://user-images.githubusercontent.com/4445313/49073734-c3fe1100-f23b-11e8-916d-57beafda4d0f.png)

Clicking on sign up with facebook or gmail is doing nothing for me.

**Comment by rogerwang** [comment]
@asteriosgr I don't think there is anything wrong with the NW on the Ubuntu machine, maybe the server blocks the IP of that machine.

For the 2nd issue, when you try to sign up with Google chrome will open a new window. With webview I believe you need to handle this with the `newwindow` event: https://developer.chrome.com/apps/tags/webview#event-newwindow

And please report separate issues for different scenarios. That would make tracking clear.

**Comment by asteriosgr** [comment]
But if my IP was blocked I would not be able to use aa.com via chromium, firefox or any other browser. Only when accessing it via the webview of nwjs it is not loading. 

Secondly, thank you for your consideration on the second issue. Yes now that you explained it I will try with the new window event. However, some issues still remain. I fixed my post above regarding issues and I removed those related to new window event.

**Comment by dansachelarie** [comment]
@rogerwang I implemented the newwin event and even if I do so it is not working. What happens is that the page opened by kayak.com is staying in infinite loading and if I open the console it said: "The user agent does not support public key credentials" - this is why I think it is related to nwjs

**Comment by asteriosgr** [comment]
@dansachelarie this is another issue. And as I can see you track it here. https://github.com/nwjs/nw.js/issues/6875

Now regarding this topic. For me the something went wrong page is still appearing. And the search functionality of other websites is affected as well.

**Comment by dansachelarie** [comment]
@rogerwang I also can confirm that the message displayed by @asteriosgr with "Something went wrong" is displayed only in the combination on nwjs + webview. In other browser it works from same pc. Also, I tried on electron + nwjs and it works.

**Comment by dansachelarie** [comment]
@asteriosgr  I know it is tracked on the other issue, but I think they are somehow related. Maybe the difference between kayak.com which remain in infinite loading screen and aa.com is that aa.com took into consideration the case when "The user agent does not support public key credentials" - and display that error page. Just a guess.

**Comment by dansachelarie** [comment]
![image](https://user-images.githubusercontent.com/31573257/49077833-011ad100-f245-11e8-8c0e-6ff02a6b293d.png)

**Comment by rogerwang** [comment]
In the original report, you referred to two sites: www.aa.com and www.aa.ro. Which one should I use trying to reproduce it? I tried aa.com and it works well for me under Linux with the latest build.

And in your test case posted in https://github.com/nwjs/nw.js/issues/6876#issuecomment-441992011 you are referring to www.google.com. It's very confusing ....

**Comment by rogerwang** [comment]
And in your original report you said it breaks on both Windows and Linux, then later, both of you said it works on Windows: https://github.com/nwjs/nw.js/issues/6876#issuecomment-441720829

Why is that happening? I'm wondering what changes on the Window machine...

**Comment by rogerwang** [comment]
@asteriosgr the blocking could be a combination if IP, cookies and user agent strings. It could be other reason as well. Anyway more information is needed to know why the server refuses your request.

**Comment by dansachelarie** [comment]
@rogerwang sorry I edited my post, initially I tested on 0.34.5 because this is the stable version of nwjs. On that one the aa.com is not working on windows. In the 0.35.0 it is working on windows but not on linux. Any idea why? (no aa.ro, only aa.com)

**Comment by asteriosgr** [comment]
> In the original report, you referred to two sites: [www.aa.com](http://www.aa.com) and [www.aa.ro](http://www.aa.ro). Which one should I use trying to reproduce it? I tried aa.com and it works well for me under Linux with the latest build.
> 
> And in your test case posted in [#6876 (comment)](https://github.com/nwjs/nw.js/issues/6876#issuecomment-441992011) you are referring to [www.google.com](http://www.google.com). It's very confusing ....

Google is simple the front page. I type aa.com and visit the site.

**Comment by rogerwang** [comment]
You could clean the user data directory and try again. And then try with `nw --url=https://www.aa.com` .

**Comment by dansachelarie** [comment]
Let me resume it because I feel somehow that we are not on the same page.

- I am trying to open https://www.aa.com inside an webview and it doesn't work (in a stable version on windows, but it works with the latest one on windows) None of those versions are working on linux. Why?

- it is not related with the IP, pc or any other stuff because it is working in another browser

- it is not related to the user data directory, I cleaned it and still same problem, also I am starting on incognito the nwjs

- from my perspective there is something which is not working in webview; in order to test it I was doing a test on electron with webview and it works. So probably it is an issue regarding the way that nwjs is integrating webview tag. (in a  normal nwjs window aa.com is working)

If you still need more information from me please let me know.
