### ISSUE TITLE
Pinning app icon to task bar on Windows creates a shortcut to `chrome_proxy.exe`

### ISSUE THREAD

**Issue by bastimeyer** [nwjs/nw.js#7033]
NWJS Version: 0.37.2
Operating System: Windows

### Expected behavior

- Pin application to task bar (right click icon and click "pin to task bar")
- Close NW.js and restart it via pinned shortcut

### Actual behavior

It tries to launch `chrome_proxy.exe` instead

### Further infos

Application code is not relevant here, as it also happens with a clean/blank NW.js app.

Related issue: #5991

**Comment by ffanny** [comment]
I can reproduce this with nwjs-sdk-win-v0.37.0.

`Target: C:\nwjs\nwjs-sdk-v0.37.0-win-x64\chrome_proxy.exe "..\..\git\nw.js\code\nwworkingdir\\"`
![image](https://user-images.githubusercontent.com/19678102/55769641-1ab20c00-5ab4-11e9-9c76-47a93377b8e2.png)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by jdfight** [comment]
https://nwjs.io/blog/v0.37.4/  lists this bug as fixed,  but I am still getting the same chrome_proxy issue when pinned to the taskbar.
