### ISSUE TITLE
new-win-policy with policy.xx anything other than ignore() fails

### ISSUE THREAD

**Issue by ka1izer** [nwjs/nw.js#7209]
NWJS Version : 0.41.2 - 0.42.3 (x64)
Operating System : Windows 10 64bits

### Expected behavior

policy.forceCurrent() should prevent ctrl+click on link from opening a new window.

### Actual behavior

It still opens a new window. .forceDownload() is also ignored, as well as setNewWindowManifest({fullscreen: true}) (only tested fullscreen=true, which did not work, don't know if other options would work).
.ignore() *does* work, though.

### How to reproduce

main:
<pre>
&lt;html&gt;
	&lt;head&gt;
		<script type="text/javascript" src="test.js"></script>
	</head>
	<body>
		<a href="test.html">Ctrl+click here</a>
	</body>
&lt;/html&gt;
</pre>

test.js:
<pre>
window.nw.Window.get().on('new-win-policy', (frame, url, policy) => {
	console.log('fired');
	policy.forceCurrent();
});
</pre>

ctrl+click on the link ("Ctrl+click here"), see "fired" in the log, but it opens in a new window.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by cdog** [comment]
Appears to still reproduce. Bumped into same issue with:
```ts
policy.setNewWindowManifest({
  show: false,
});
```
The new window is still visible regardless. Testing with NW.js v0.60.1.

**Comment by cdog** [comment]
Any updates on this? Since `policy.setNewWindowManifest` doesn't work (before window is created), hiding the window later via `chrome.windows.onCreated` as a temporary fix (after window is created) getting a flickering effect.
