### ISSUE TITLE
nw2: Window icon cannot be set

### ISSUE THREAD

**Issue by Luzzifus** [nwjs/nw.js#7222]
NWJS Version : 0.42.5
Operating System : Win10 (1903)

### Expected behavior

When specifying the window subfield "icon", the taskbar icon of the window should display that icon.

### Actual behavior

The taskbar icon shows a default document icon.

![icon_error](https://user-images.githubusercontent.com/431996/69134240-75cec700-0ab7-11ea-86a1-494bdef8030d.png)

### How to reproduce

Only happens in NW2 mode, works as expected with "chromium-args": "--disable-features=nw2".

    nw.Window.open('html/index.html', {
      show: false,
      frame: false,
      icon: 'html/icon/icon128.png',
      title: 'Whatever',
      width: 850,
      height: 600,
      position: 'center'
    });

#7230

**Comment by rogerwang** [comment]
This was fixed in #7236

**Comment by akshay-joshi** [comment]
I am still facing this issue while developing my application.

**Scenario**: My application launches multiple new windows depending on the condition set by the users. I used "window.open(url, '_blank');" which is an existing logic that I can't change. 

To set the common height, width and icon for all windows I used the below logic:

currWin.on('new-win-policy', function(frame, url, policy) {
policy.setNewWindowManifest({
    'icon': '../assets/app.png',
    'frame': true,
    'width': 1300,     
    'height': 900,     
    'position': 'center',
  });
});

The above is working fine on OSX, but when runs on Windows 10 I am still getting a red icon for the newly open window. Please refer to the below screenshot.
<img width="149" alt="Screenshot 2020-12-03 at 6 17 36 PM" src="https://user-images.githubusercontent.com/1632882/101021870-848afd80-3596-11eb-931f-64ce941a5edf.png">

**When I use --disable-features=nw2 it works.**

**Using**: nw.js v0.50.1
<img width="352" alt="Screenshot 2020-12-03 at 6 17 16 PM" src="https://user-images.githubusercontent.com/1632882/101021867-8228a380-3596-11eb-98d1-83fcd5ccfed1.png">
