### ISSUE TITLE
nwjs taskbar icon on Windows for NW.js is a red square, can't set icon in package.json

### ISSUE THREAD

**Issue by frankhale** [nwjs/nw.js#7236]
NWJS Version : 0.42.5 SDK version
Operating System : Windows 10 (x64)

### Expected behavior

You should be able to set the icon associated with NW.js using the provided method of setting "icon" in the "window" section of the package.json file.

### Actual behavior

The icon associated with the NW.js application is a red square and cannot be set using the provided methods in the package.json. See screenshot in the comments below.

### How to reproduce

Download 0.42.5 SDK for Windows x64 and set your package.json to be like:

**NOTE: This is not a path problem as it works fine in 0.40.**

```javascript
{
  "name": "app-name-here"
  "main": "index.html",
  "window": {
    "icon": "image.png"
  }
}
```

**Comment by rogerwang** [comment]
Could you provide a sample of the icon? It works for me.

**Comment by Blatman** [comment]
@rogerwang 
Not sure what is going on but I get the same thing - I tried the app on #7221 (transparency issue) and the icon is red square with nw2 (see attached graphic on #7221). I also tried one of my apps which works ok on OSX (apart from the shadow issue) and it also fails on nw2 - I get the red icon. All is OK if nw2 is disabled in the manifest.
I think that #7222 is the same issue also.
I was using Win 10 Pro 64bit (1803) in Parallels 13 VM on OSX 10.13.6.

**Comment by frankhale** [comment]
Just running NW.js demonstrates the behavior. Here is a screenshot of it:

![image](https://user-images.githubusercontent.com/190154/69496374-90ca7e00-0e9f-11ea-9c2e-78cc28580180.png)

**Comment by zhsunlight** [comment]
the same to me

**Comment by kucix** [comment]
Same here
![image](https://user-images.githubusercontent.com/444459/69539440-c39a7200-0f84-11ea-9b56-6289240bfc32.png)

**Comment by sascha-schieferdecker** [comment]
I can confirm this issue

**Comment by khoshrou** [comment]
I have this problem too

**Comment by rogerwang** [comment]
interesting ... it works for me with win10 and the default app. Could you try to clear the icon cache?
https://www.winhelponline.com/blog/how-to-rebuild-the-icon-cache-in-windows/#script

<img width="578" alt="iconscreenshot" src="https://user-images.githubusercontent.com/165401/69779662-b9c27a00-11e3-11ea-9bb8-60c8d1f6f190.png">

**Comment by zhsunlight** [comment]
it works with latest (v0.43.0), but not with v0.42.5

**Comment by kucix** [comment]
> interesting ... it works for me with win10 and the default app. Could you try to clear the icon cache?
> https://www.winhelponline.com/blog/how-to-rebuild-the-icon-cache-in-windows/#script

If I switch between 0.42.3 and 0.42.5, icon work in 0.42.3 and doesn't work in 0.42.5, so it's not icon cache (and users won't clear it)

Same just now with clean base, only extracted.
I tested both 32 and 64 bit version and both SDK and non-SDK versions with same results.


![image](https://user-images.githubusercontent.com/444459/69782450-5d466700-11b1-11ea-9611-37e0e6c4a2c5.png)

![image](https://user-images.githubusercontent.com/444459/69782472-6fc0a080-11b1-11ea-88c8-feecd2aca91a.png)

**Comment by khoshrou** [comment]
I just tested clean cache script and it still not working
I still see a big red square

**Comment by rogerwang** [comment]
Does `--disable-features=nw2` make any difference there?

**Comment by kucix** [comment]
yes,

standard run (0.42.5, 32b)
![image](https://user-images.githubusercontent.com/444459/69788025-e9f72200-11bd-11ea-8da7-facf202a2738.png)

disable nw2  (0.42.5, 32b)
![image](https://user-images.githubusercontent.com/444459/69788093-0a26e100-11be-11ea-90f0-306ade54bd7b.png)

It's possible setting this flag in package.json? Or it's only command line argument?

**Comment by khoshrou** [comment]
Yes it differs
with --disable-features=nw2
![image](https://user-images.githubusercontent.com/5165520/69788166-25e8b200-11d3-11ea-8549-298e47515747.png)

normal
![image](https://user-images.githubusercontent.com/5165520/69788200-3c8f0900-11d3-11ea-9217-2cfffef804a2.png)

**Comment by rogerwang** [comment]
Yes. It can be used in `package.json` for now as a workaround.

**Comment by kucix** [comment]
If I added `--disable-features=nw2` to package.json, everything seems fine, but I can't open downloaded files - #7234

**Comment by rogerwang** [comment]
I managed to reproduce it in another system. This is now fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by frankhale** [comment]
Thank you to everyone on this issue. You guys rock!

**Comment by akshay-joshi** [comment]
I am still facing this issue while developing my application.

**Scenario**: My application launches multiple new windows depending on the condition set by the users. I used "window.open(url, '_blank');" which is an existing logic that I can't change. 

To set the common height, width and icon for all windows I used the below logic:

currWin.on('new-win-policy', function(frame, url, policy) {
policy.setNewWindowManifest({
'icon': '../assets/app.png',
'frame': true,
'width': 1300,     
'height': 900,     
'position': 'center',
});
});

The above is working fine on OSX, but when runs on Windows 10 I am still getting a red icon for the newly open window. Please refer to the below screenshot.
<img width="149" alt="Screenshot 2020-12-03 at 6 17 36 PM" src="https://user-images.githubusercontent.com/1632882/101022299-362a2e80-3597-11eb-91ac-31908cc15222.png">

**When I use --disable-features=nw2 it works.**

**Using**: nw.js v0.50.1
<img width="352" alt="Screenshot 2020-12-03 at 6 17 16 PM" src="https://user-images.githubusercontent.com/1632882/101022390-5823b100-3597-11eb-97bb-80da01fa0f58.png">

**Comment by akshay-joshi** [comment]
Hi All

Tray icon is not visible as well. Below is the logic that I have used
    var trayObject = new gui.Tray({
      title: 'MyApp',
      tooltip: 'MyApp is running',
      icon: '../../assets/myApp.png',
    });

My code structure is : 
assets -> myApp.png (1024 x 1024) 
src -> js -> index.js (creating tray object here. Refer above code)

**Comment by akshay-joshi** [comment]
Hi All

Tray icon is not visible as well. Below is the logic that I have used:

var trayObject = new gui.Tray({
title: 'MyApp',
tooltip: 'MyApp is running',
icon: '../../assets/myApp.png',
});

**My code structure is** :
assets -> myApp.png (1024 x 1024) tried myApp.ico (256 x 256) as well but didn't worked.
src -> js -> index.js (creating tray object here. Refer above code)

**Comment by YodaLightsabr** [comment]
Yes, I'm having the same issue.
![image](https://user-images.githubusercontent.com/76178582/106398642-e87c4780-63c8-11eb-8ec2-899220f954c6.png)
It doesn't happen in my main window, but since it uses an <iframe>, when the iframe opens a new window with the _blank target, it makes a new window with a red square, and all new windows stack on the red square, rather than the original icon.

**Comment by codeweapon** [comment]
I can confirm that this issue with the taskbar icon for Windows 10 still persists. I am using the 0.51.1 version of nw.js and the taskbar icon always defaults doesn't matter what I am doing. Even though the .exe icon is changing on the build and behaves as expected.

**Comment by rogerwang** [comment]
Could you provide a full sample including your icon file? It works for me with the sample from #4581

**Comment by codeweapon** [comment]
@rogerwang Thank you for your reply. I figured it out. I had a small size for the icon and that's why it didn't work. Now I'm using 256 x 256 and looks like it's a safe size. There is a lot of confusion with the taskbar icon because it has to be png, not .ico and it needs to be a specific size. I worth pointing out that part in the documentation in more detail.

**Comment by rogerwang** [comment]
Could you upload your icon? I can look to fix it.

**Comment by akshay-joshi** [comment]
![pgAdmin4](https://user-images.githubusercontent.com/1632882/108701312-c724fc00-752d-11eb-9ed4-10ec62d2fb87.png)

**Comment by codeweapon** [comment]
@rogerwang Thank you for your attention. I tried to use a smaller icon 48x48 and it didn't work for me. Just showing up as a default one.
<br>
<img src="https://raw.githubusercontent.com/codeweapon/nwjsicon_issue/main/icon_error.png"></img>

**Comment by troywoy** [comment]
I too am seeing a red icon while using `0.52.1`, but only for newly opened windows. The image below shows the app icon (next to Notepad) correctly for the first window, then I used the app which triggered a normal `window.open` that resulted in the red square icon.

<img width="96" alt="Screen Shot 2021-03-31 at 2 31 29 PM" src="https://user-images.githubusercontent.com/1566003/113193310-d46c8f00-922d-11eb-87aa-3ce9c350f0c7.png">

I saw a suggestion saying to try disabling nw2 but then read that caused downloaded files to possibly fail. Any suggestions or guidance would be great as I'm pretty new to NW.js.

**Comment by panther7** [comment]
NWjs 0.53.0

Hotkey Ctrl+U (Windows)

![2021-05-04 12 09 27](https://user-images.githubusercontent.com/3808250/116989178-b0d7b100-acd1-11eb-8878-4da59233a63e.png)

**Comment by adityatoshniwal** [comment]
Any workaround or fix for this please ?

**Comment by anilsahoo20** [comment]
Hi @rogerwang 
We are still facing this issue in pgAdmin 4. Any update on this please?

**Comment by ImSpyke** [comment]
## 📚 The icon guide to fix everything
Or i hope most of the issues you could encounter like me.

### 🪟 Change window icon (top-left)
![image](https://github.com/user-attachments/assets/665a8571-6203-426c-be51-ed19b7023ed4)
Eitheir directly into the html, or in your package.json by adding the following key:
```json5
// package.json
{
    // ...
    "window": {
        "icon": "path.png"  // Relative path are from the NW.exe location. Image cannot be .ico
                            // Image needs to be a perfect square to not be streched.
                            // However, too large images are slower to load so consider putting 128px to 1024px size instead of a 240MB 4K full HD image-
        // "toolbar": true,         // Not necessary
        // "width": 1000,           // Not necessary
        // "height": 800,           // Not necessary
        // "position": "center",    // Not necessary
        // "resizable": true        // Not necessary
    },
    // ...
}
```

### 💻Change taskbar icon
![image](https://github.com/user-attachments/assets/416c29ea-9f1d-4e25-bd55-d90466915e05)
You can add the following key in your package.json file:
```json5
// package.json
{
    // ...
    "icons": {
        "256": "path.png" // Relative path are from the NW.exe location. Image cannot be .ico
        // Image doesn't need to be 256px, but needs to be a perfect square to not be streched.
        // However, too large images are slower to load so consider putting 128px to 1024px size instead of a 240MB 4K full HD image-
    },
    // ...
}

```

### 📲 Change executable icon
![image](https://github.com/user-attachments/assets/d34398b6-b1e3-47c6-8b3e-dbc8ed940485)
By using [Ressource Hacker](https://www.angusj.com/resourcehacker/) you will be able to change the icon of the file.
Tutorial here: https://www.youtube.com/watch?v=QD1xJjhEypg
After editing the icon, you might not see it directly.
To refresh the icon cache of windows without restarting your computer you can open a Powershell terminal and run `ie4uinit -show`

### 🖥️ Change Tray icon (bottom right of your desktop)
![image](https://github.com/user-attachments/assets/ec002ae6-80a5-4265-ae1d-624fc11622f7)
Simply add in your script
```js
// if nw is undefined use require("nw.gui") instead
var tray = new nw.Tray({
    title: 'Tray name', // Mac only as Windows displays natively the icon
    tooltip: 'Hover text', // In my example picture its "POG Cardinal 2"
    icon: "path.png", // Relative path are from the NW.exe location. Image cannot be .ico
});
```

### 🟥 Workarounds red square on new opened windows
![image](https://github.com/user-attachments/assets/714e3f53-6471-4e6e-9114-62de0c21498e)
#### Best fix
The best workaround i've found that far is this one, from [this issue](https://github.com/nwjs/nw.js/issues/5822).
Basically, in your script you'll redefine how new opened windows should be instancied, and then pass it to the NW function which ensure a window opened with the icon (and actually stacked like Chrome onto each others).
![image](https://github.com/user-attachments/assets/278d8a05-da7a-4343-8559-26c23bd1c3db)
```js
require('nw.gui').Window.get().on('new-win-policy',function(frame, url, policy){
    policy.ignore();
    // The lext line open a new window with the red square issue
    // chrome.windows.create({url:"https://google.com",type:"normal",focused:true});
    //The next line open a new window stacked with the main one.
    require('nw.gui').Window.open(url,{frame:true,focus:true}); // {frame:true,focus:true} is not necessary
});
```
You can also use it in standalone directly with using
`require('nw.gui').Window.open("your url");` instead of `open(url)`. But the code above also fixes the new pages opened by the `<a>link</a>` tags.

#### Other fix
You can add the following into your package.json, but keep in mind that this is not intended to fix this bug specifically.
As written, you'll be disabling the `nw2` features, which can lead to potential other issues. Use at your own risk.
```json5
// package.json
{
    // ...
    "chromium-args": "--disable-features=nw2"
    // ...
}
```

## ❔ Sources
- You guys, to help me figure out every issues
- Ressource hacker turorial: https://www.youtube.com/watch?v=QD1xJjhEypg
- New window chrome policy fix: https://github.com/nwjs/nw.js/issues/5822

**Comment by frankhale** [comment]
Closing this issue since it's 5 years old and there is no new response by developer.

The guide just posted seem to be the best way to work around the problems.
