### ISSUE TITLE
Cant use worker threads

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#7273]
Trying to run the following code using NW.js v0.43.0 returns "Error: The V8 platform used by this instance of Node does not support creating Workers"

```
const { Worker } = require('worker_threads');

const worker = new Worker('const { parentPort } = require("worker_threads");parentPort.once("message",message => parentPort.postMessage({ pong: message }));  ', { eval: true });
worker.on('message', message => console.log(message));      
worker.postMessage('ping');  
```

**Comment by Dimtime** [comment]
This related issue: https://github.com/nwjs/nw.js/issues/7114

**Comment by rogerwang** [comment]
Close as duplicate. Thanks.

**Comment by rogerwang** [comment]
The fix is released in 0.44.0 beta1

**Comment by elpeleq42** [comment]
its not fixed @rogerwang actually it was made much worse in v0.44.1

trying to run the same code now crashes the page and the window closes if I try opening the console. Running it without a page, just a .js file(and changing console.log by alert so I can see a message) does nothing so I assume it also breaks the same way.

trying to open nwjs sdk and paste the code on the console also makes the page crash and the dev tools simply gets disconnected with no errors

**Comment by rogerwang** [comment]
Please check and post updates in #7114. This issue is the duplicate of it.
