### ISSUE TITLE
NW.js crashes soon after opening

### ISSUE THREAD

**Issue by elpeleq42** [nwjs/nw.js#7450]
The second I open my app, after updating it from nw.js v0.45.3 to v0.45.4 (windows 10), windows' firewall asked for permission to run it and it crashed. Trying to open it again will crash one more time, without any ask for permission.
I haven't tested this on Linux or mac, but it occurs with both the normal and SDK versions.

debug.txt had the following lines:

[0423/190733.934:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: A operação foi concluída com êxito. (0x0)
[0423/190738.424:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: A operação foi concluída com êxito. (0x0)
[0423/190759.190:ERROR:http_transport_win.cc(178)] WinHttpCrackUrl: A operação foi concluída com êxito. (0x0)

My app was throwing no errors before updating nwjs. My app is a visual interface for the server script of my game(it uses websockets)

**Comment by rogerwang** [comment]
Could you please provide a sample so I can reproduce it? The error message you provide is not relevant.

**Comment by elpeleq42** [comment]
> Could you please provide a sample so I can reproduce it? The error message you provide is not relevant.

well apparently its something related to worker threads... again...

running the following code on the chromium console(windows 10, nwjs v0.45.4 sdk) crashes it:

```
const { Worker } = require('worker_threads');
const worker = new Worker('const { parentPort } = require("worker_threads");parentPort.on("message",message => parentPort.postMessage({ pong: message }));  ', { eval: true });
worker.on('message', message => console.log(message));      
worker.postMessage('ping');
```
 
Thats why I suggested better and more extensive tests. This same problem was occuring up to 6 or so updates ago, then a fix was made (which didnt actually fix it until 1 version after that).

Please add the above code as part of the auto testing script for NW.js

**Comment by elpeleq42** [comment]
I'm also guessing something related to HTTP or websockets may also cause crashes, because on the client side when I use location.reload() and then connect to a server(which uses websockets), the client crashes(thing that also wasn't happening back in 0.45.3)

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by TheRealDannyyy** [comment]
@rogerwang This is not fixed. It still just closes after ~20sec, probably related to worker mode.
I just used Construct 3, here is the package file: [package.zip](https://github.com/nwjs/nw.js/files/4575768/package.zip)

_Request to reopen issue to investigate and fix._

**Comment by elpeleq42** [comment]
can confirm that a crash still is happening after around 20 seconds @rogerwang

**Comment by rogerwang** [comment]
It should be different root cause as the test case is passing. Please file another issue with sample to reproduce.
