### ISSUE TITLE
[0.46.1] Trying to access process.env or global.process.env the application crashes..

### ISSUE THREAD

**Issue by DimPaDev** [nwjs/nw.js#7493]
NWJS Version : 0.46.1
Operating System : Linux, Windows

### Expected behavior

If you try to access **process.env** or **global.process.env** in the code or from the dev tools console the application should not crash.

### Actual behavior

The nw.js application crashes completely without warnings or errors 

### How to reproduce

Just run a hello world application using this snippet : 
```

<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using node.js <script>document.write(process.version)</script>.
    Trying to access <script>document.write(process.env)</script>.
    Trying to access <script>document.write(global.process.env)</script>.
  </body>
</html>
```

**Comment by DimPaDev** [comment]
The same issue persists on Windows 10

**Comment by krneticz** [comment]
I have experienced the same. Tested on Windows Server 2016, process.env crashes nwjs. But I can also confirm that in nwjs 0.46.0 it DOES NOT cause the crash.

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by DimPaDev** [comment]
I confirm this is fixed in the latest nightly build! Thanks

**Comment by krneticz** [comment]
@rogerwang @DimPaDev I just tested nwjs-sdk-v0.46.1-win-x64 and it still crashes when I do process.env from the console!

**Comment by DimPaDev** [comment]
@krneticz this is fixed in the latest version (0.46.2)

**Comment by krneticz** [comment]
@DimPaDev you are right! It is fine in 0.46.2. Thanks!
