### ISSUE TITLE
Our sourcemaps no longer loading in v0.52.0 and later

### ISSUE THREAD

**Issue by bswanwick** [nwjs/nw.js#7724]
NWJS Version : nwjs-sdk-v0.52.0-win-ia32
Operating System : Windows 10 Pro

### Expected behavior

Sourcemaps should load like they do in v0.51.2

### Actual behavior

After updating to v0.52.0 we get ERR_BLOCKED_BY_CLIENT in console for our sourcemaps.  Tested this in v0.53.0 as well.  Sourcemaps do load correctly in v0.51.2 

### How to reproduce

Reproducing it exactly on your end may be difficult, but here's a screen grab of console.  Using the SDK from v0.51.2 works fine and sourcemaps are loading.  But updating to SDK v0.52.0 and later breaks it...

![sourcemaps_missing](https://user-images.githubusercontent.com/7740392/117479011-d3660600-af2d-11eb-8d96-5dd7ce4e599c.PNG)

**Comment by corwin-of-amber** [comment]
Same with 0.53.1 and 0.54.0.

**Comment by corwin-of-amber** [comment]
I think this happens with all sourcemaps regardless of origin. But if it helps reproducing, here is the app that I've been using with 0.54.0.
Strange, if I try to `fetch()` the very same URL that devtools is complaining about, I do not get an ERR_BLOCKED_BY_CLIENT.
[suslik.tar.gz](https://github.com/nwjs/nw.js/files/6562778/suslik.tar.gz)

**Comment by trethaller** [comment]
Same problem, downgraded to 0.51.2 and it works fine

**Comment by Cubelrti** [comment]
Upstream crbug: https://crbug.com/974543 and https://crbug.com/1052872

Not a nw issue actually, just wait for Chromium update.

**Comment by corwin-of-amber** [comment]
I can confirm that now (0.55.0) it really only happens on `chrome-extension://`, so a viable hack for debugging is to set the URLs of the `.map` files to absolute `file://` URLs.

I am using the following setting in my `webpack.config.js`:
```
  devtool: false,
  plugins: [
    new webpack.SourceMapDevToolPlugin({
      append: `\n//# sourceMappingURL=file://${__dirname}/dist/[url]`,
      filename: '[name].map'
    })
  ]
```

**Comment by zinuru** [comment]
Same in 0.55.0 and now in 0.56.0 :-(

**Comment by zkrige** [comment]
same in 0.56.1

**Comment by corwin-of-amber** [comment]
It looks like the latest build (0.58.1) includes the fix. At least, my sourcemaps are showing now 😄

**Comment by zkrige** [comment]
@corwin-of-amber not seeing the fix in 0.60.0

**Comment by bswanwick** [comment]
Same, can confirm my source maps don't load either in latest nwjs build.

**Comment by zinuru** [comment]
I solved this problem. Moved to Tauri. Easy setup, everything works, no dependency worries, small footprint. As a side benefit, you get to learn Rust which frees you from other legacy luggage. Happy coding!

**Comment by corwin-of-amber** [comment]
@zkrige @bswanwick Curious — my source maps still work in both 0.59 and 0.60, although I now notice that the mapped filenames do not appear in the source listing to the left. Ctrl+P (or Cmd+P) then typing the filename does find them. Is your case similar?
<img width="946" alt="Screen Shot 2022-01-27 at 19 31 18" src="https://user-images.githubusercontent.com/704372/151412584-d99817b9-de63-4af8-b795-74a8d7be08f1.png">

@zinuru 😅

**Comment by corwin-of-amber** [comment]
@zkrige @bswanwick Ok strike that, it turns out I was using inline maps in that particular project 😓
When I switch to linked map files I definitely get ERR_BLOCKED_BY_CLIENT, so yes, definitely still an issue.
🦢

**Comment by zkrige** [comment]
this appears fixed in 0.62.1 👏

**Comment by Regiden** [comment]
Yes it seems to be fixed. However on 63.0 at least we seem to get broken Code highlighting. 

![grafik](https://user-images.githubusercontent.com/1666633/163327338-b6b34be3-7cd8-44a4-b7d1-dbdbc9441ad3.png)

This is just a function in a class and it seems to only sometimes correctly render colors for some line. The code is otherwise valid and the JS variant also renders fine.

**Comment by ayushmxn** [comment]
Fixed in upstream

**Comment by aggregate1166877** [comment]
It did not work for me out of the box. 

For people who still have issues, this solved it for me:
* Right click inside the text of the uglified file, click `Add source map...`
* When it prompts you for the source map path, specify the full absolute `file:///` path (example `/home/my_user/myProject/build/app.source.map`)
